<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_transifex_tmgmt_translator_plugin_info() {
  return array(
    'transifex' => array(
      'label' => t('Transifex translator'),
      'description' => t('Transifex Translator service.'),
      'plugin controller class' => 'TMGMTTransifexTranslatorPluginController',
      'ui controller class' => 'TMGMTTransifexTranslatorUIController',
      'default settings' => array(
        'api' => '',
        'tx' => '',
        'project' => '',
      ),
    ),
  );
}

/**
 * Validation callback for the plugin settings form.
 */
function tmgmt_transifex_plugin_settings_form_validate($element, &$form_state, $form) {
  $settings = $form_state['values']['settings'];
  // Only validate the API key if one was provided.
  if (empty($settings['api'])) {
    return;
  }

  /** @var TMGMTTranslator $translator */
  $translator = $form_state['tmgmt_translator'];
  // Update translator settings with form data.
  $translator->settings = $settings;
  /** @var TMGMTTransifexTranslatorPluginController $controller */
  $controller = $translator->getController();
  if (!$controller->getTransifexProject($translator)) {
    form_error($element, t('The "Transifex API Key" is not valid or the target transifex project does not exist.'));
  }
}

/**
 * Implements hook_menu().
 */
function tmgmt_transifex_menu() {
  $items['tmgmt_transifex/webhook'] = array(
    'title' => 'Transifex webhook',
    'page callback' => 'tmgmt_transifex_validate_webhook',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Page callback for /hello.
 */
function tmgmt_transifex_validate_webhook() {
  $http_verb = 'POST';
  $http_url_path = drupal_get_http_header('Http-X-Tx-Url');
  $http_gmt_date = drupal_get_http_header('Http-Date');
  $content_md5 = md5($_POST['content']);
  $msg = join('\n', ['POST', http_url_path, http_gmt_date, content_md5]);
  $sig = hash_hmac('sha256', $msg, '12345' );
  watchdog('tmgmt_transifex', join('\n', [$sig, drupal_get_http_header('Http-X-Tx-Signature-V2')]));
  return drupal_json_output($data);
}
