<?php

/**
 * @file
 * Module file of the translation management test module.
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_transifex_tmgmt_translator_plugin_info() {
  return array(
    'transifex' => array(
      'label' => t('Transifex translator'),
      'description' => t('Transifex Translator service.'),
      'plugin controller class' => 'TMGMTTransifexTranslatorPluginController',
      'ui controller class' => 'TMGMTTransifexTranslatorUIController',
      'default settings' => array(
        'api' => '',
        'tx' => '',
        'project' => '',
      ),
    ),
  );
}

/**
 * Validation callback for the plugin settings form.
 */
function tmgmt_transifex_plugin_settings_form_validate($element, &$form_state, $form) {
  $settings = $form_state['values']['settings'];
  // Only validate the API key if one was provided.
  if (empty($settings['api'])) {
    return;
  }

  /** @var TMGMTTranslator $translator */
  $translator = $form_state['tmgmt_translator'];
  // Update translator settings with form data.
  $translator->settings = $settings;
  /** @var TMGMTTransifexTranslatorPluginController $controller */
  $controller = $translator->getController();
  if (!$controller->getTransifexProject($translator)) {
    form_error($element, t('The "Transifex API Key" is not valid or the target transifex project does not exist.'));
  }
}

/**
 * Implements hook_menu().
 */
function tmgmt_transifex_menu() {
  $items['tmgmt_transifex/webhook'] = array(
    'title' => 'Transifex webhook',
    'page callback' => 'tmgmt_transifex_validate_webhook',
    'access callback' => TRUE,
  );
  return $items;
}

function transifex_prepare_translation($translations) {
  $payload = array();
  $keys = array_keys($translations);
  $bodyCount = 0;
  // Deal with the bodies
  while (in_array('body_' . $bodyCount, $keys) || in_array('body_' . $bodyCount . '_sentence_0', $keys)) {
    if (in_array('body_' . $bodyCount, $keys)) { // Non segmented body
      $payload['body'][$bodyCount]['#text'] = $translations['body_' . $bodyCount];
      unset($translations['body_' . $bodyCount]);
    } else { // Segmented case - recompose
      $composed = '';
      $sentence_count = 0;
      while (isset($translations['body_' . $bodyCount . '_sentence_' . $sentence_count])) {
        $composed .= $translations['body_' . $bodyCount . '_sentence_' . $sentence_count];
        unset($translations['body_' . $bodyCount . '_sentence_' . $sentence_count]);
        $sentence_count++;
      }
      $payload['body'][$bodyCount]['value']['#text'] = $composed;
      $bodyCount++;
      $keys = array_keys($translations);
    }
  }
  // Deal with the rest
  foreach ($translations as $key => $translation) {
    if (preg_match('/(.*)_(\d+)$/', $key, $matches)) {
      $payload[$matches[1]][$matches[2]]['value']['#text'] = $translation;
    } else {
      $payload[$key]['#text'] = $translation;
    }
  }
  return $payload;
}

/**
 * Page callback; gitHub WebHook endpoint.
 */
function tmgmt_transifex_validate_webhook() {
  $received_json = file_get_contents("php://input",  TRUE);
  $webhook = drupal_json_decode($received_json, TRUE);

  $translator = tmgmt_translator_load('transifex');
  $tx = new TransifexApi($translator);
  $http_verb = 'POST';
  $webhook_sig = $_SERVER['HTTP_X_TX_SIGNATURE_V2'];
  $http_url_path = $_SERVER['HTTP_X_TX_URL'];
  $http_gmt_date = $_SERVER['HTTP_HTTP_DATE'];
  $content_md5 = md5($received_json);
  $msg = join(PHP_EOL, array('POST', $http_url_path, $http_gmt_date, $content_md5));
  $sig = base64_encode(hash_hmac('sha256', $msg, '12345', true));

  if (1 == 1) {// $sig == $webhook_sig) {
    // Change array of objects to hashmap
    $translations = array_reduce($tx->getTranslations($webhook['resource'], $webhook['language']), function ($result, $item) {
      $result[$item->key] = $item->translation;
      return $result;
    }, array());
    // Prepare translation payload for body
    $body = '';
    $bodyCount = 0;
    $node_id = intval(end(explode('_', $webhook['resource'])));

    foreach ($tx->getResource($webhook['resource'])->categories as $category) {
      preg_match('/tjid:(.*)/', $category, $tjid);
      if ($tjid[1]) {
        $tjid = intval($tjid[1]);
        $job = tmgmt_job_load($tjid);
        foreach ($job->getItems() as $tjiid => $job_item) {
          if ($job_item->item_id == $node_id) {
            //echo json_encode($job_item);
            $job->addTranslatedData(
              array($tjiid => transifex_prepare_translation($translations))
            );
          }
        }
      }
    }
  } else {
    echo 'Invalid webhook';
  }
}

function github_webhook_payload() {
  $payload = &drupal_static(__FUNCTION__);
  if (NULL === $payload) {
    $payload = (isset($_POST['payload'])) ? drupal_json_decode($_POST['payload']) : array();
  }
  return $payload;
}

/**
 * Delivery callback; Convets the array to JSON and returns.
 *
 * @param array $page_callback_result
 *   The result of a page callback. The array is simply converted to JSON, which
 *   is the rendered output of the page request.
 */
function tmgmt_webhook_json_deliver(array $page_callback_result) {
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
  print drupal_json_encode($page_callback_result);
  module_invoke_all('exit');
  drupal_session_commit();
}
